name: 'CI'
on: [push]
jobs:

  docker:
    name: 'Push docker image'
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:source"
          push: true
          tags: micheb/remote-unit-tests:latest

  test:
    name: 'Run unit tests'
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: pull and run docker image on the host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        script: |
          docker pull micheb/remote-unit-tests:latest
          docker run micheb/remote-unit-tests:latest
          ID=$(docker ps -a | grep micheb/remote-unit-tests:latest | head -n1 | sed -e 's/\s.*$//')
          docker stop $ID
          docker rm $ID
